create table if not exists public.fokus_stores (
 id bigint generated by default as identity primary key,
 store text not null unique,
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.fokus_metrics (
 id bigint generated by default as identity primary key,
 store text not null references public.fokus_stores(store) on update cascade,
 period text not null,
 indicator text not null,
 target numeric not null default 0,
 actual numeric not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(store,period,indicator)
);

create index if not exists fokus_metrics_store_period_idx on public.fokus_metrics(store,period);
alter table public.fokus_stores enable row level security;
alter table public.fokus_metrics enable row level security;
revoke all on public.fokus_stores from anon,authenticated;
revoke all on public.fokus_metrics from anon,authenticated;
grant all on public.fokus_stores to service_role;
grant all on public.fokus_metrics to service_role;

-- Tambahkan kode toko awal, contoh:
-- insert into public.fokus_stores(store) values ('T001');
